import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ballprint",
  description: "Generated by Ballprint",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 left-0 flex h-full w-full items-center justify-center bg-[rgba(147,137,229,0.1)] backdrop-blur-[10px]">
          <div className="relative flex h-full w-full max-w-[528px] flex-col bg-white p-6 sm:h-[95vh] sm:rounded-3xl sm:shadow-[0_4px_6px_-1px_rgba(0,0,0,0.1),_0_2px_4px_-1px_rgba(0,0,0,0.06)] overflow-hidden">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
